### ISSUE TITLE
환경 설정 추기: GraphQL 도입

### ISSUE THREAD

**Issue by JungKyuHyun** [JungKyuHyun/Admin-project-api#7]
## 도입 취지
캔의 요청으로 기술 스택으로 GraphQL을 도입 검토

## 고려해야 할 부분

1. 기존 프론트와 백엔드는 GraphQL을 고려하지 않은 설계다. 
2. 러닝 커브 - 나는 해본적은 있지만, 캔은 해본적이 없다. 실제 프로덕션에서 사용해 보지 않았기 때문에 설계에 대한 부분에 더 많은 시간을 쏟아야 한다. 
3. 수 많은 Tool - 뭘 쓰죠.. 무난하게 아폴로?

<hr />

# GraphQL
도입 전에 간략하게 캔에게 전달.

## GraphQL은 무엇인가?
API를 생산하는 쿼리 언어이다.

## 좋은점이 무엇인가?
좀 더 flexible하게 데이터에 접근할 수 있다. 
서버의 변경없이 새로운 쿼리를 클라이언트단에서 보낼 수 있다.

## 단점은 무엇인가?
러닝커브 - useful한 스키마를 작성하기 위해서는 skill이 필요하다.

## 대체제는 무엇이 있는가?
Restful API를 사용할 수 있다. (완전 대체제를 의미하지는 않지만, 논의의 편의를 위해 대체제라고 생각하면 좋을거 같다.)

## 실제 GraphQL을 사용하는 곳
페이스북, github 등...

**Comment by JungKyuHyun** [comment]
고려해야 할 부분에 대한 답변과 이외의 캔의 생각 등을 말씀해 주시면 좋을거 같아요.

**Comment by ghojeong** [comment]
여러 회사에서는 무난하게 Apollo 를 가장 많이 쓰는 것 같습니다.
Apollo 를 사용하는데 동의합니다.

제가 만들고 있는 그래프와 테이블을 통한 데이터 시각화에서는, 알파 때는 지역별로 나뉘는 남자, 여자, 총 인구수를 보여주기만 할 것이지만,
베타때는 시계열에 따라 데이터를 보여주고 싶습니다.

지역, 시간, 성별 3가지 axis 로 데이터를 조회하거나 다룰 수 있도록 스키마 설계 부탁드립니다.

**Comment by JungKyuHyun** [comment]
음.. 
요약하면....
1. (모르겠고) 도입하자.
2. 러닝 커브 -> (모르겠고) 스키마를 이렇게 설계해 달라 ㅋㅋㅋ
3. 아폴로 쓰자.

환상적인 답변 감사합니다 :) ....
도입하도록 하겠습니다.

**Comment by ghojeong** [comment]
찰떡같이 알아들으셨군요. 아주 훌륭합니다. 😆
